// Generated by CoffeeScript 1.6.3
var dirname, fs, local;

fs = require('fs');

dirname = require('path').dirname;

local = {
  sources: {},
  recurse: function(opts) {
    var error, path, recursing;
    if ('string' === typeof opts) {
      path = opts;
    }
    try {
      recursing = function(path, array, vertex, stack) {
        var error;
        if (stack == null) {
          stack = [];
        }
        try {
          return array.map(function(next) {
            var meta;
            path += '/' + next;
            stack.push(next);
            /* establish type is [file|dir]*/

            if (fs.lstatSync(path).isDirectory()) {
              vertex[next] || (vertex[next] = {});
              vertex[next].meta = {
                type: 'dir',
                path: path
              };
              recursing(path, fs.readdirSync(path), vertex[next], stack);
              path = dirname(path);
              return stack.pop();
            }
            /* files get a handler*/

            meta = {
              type: 'file',
              path: path
            };
            vertex[next] = function(opts, callback) {
              return callback(null, {
                result: {}
              });
            };
            vertex[next].meta = meta;
            return stack.pop();
          });
        } catch (_error) {
          error = _error;
          return console.log({
            e2: error
          });
        }
      };
      return recursing(path, fs.readdirSync(path), local.sources);
    } catch (_error) {
      error = _error;
      return console.log({
        e1: error
      });
    }
  }
};

module.exports = function(opts) {
  var error, path, stat;
  if ('string' === typeof opts) {
    path = opts;
    try {
      stat = fs.lstatSync(path);
      if (stat.isDirectory()) {
        return local.recurse(path);
      }
    } catch (_error) {
      error = _error;
      return console.log(error);
    }
  }
};

module.exports._testInstance = local;
