// Generated by CoffeeScript 1.6.3
var fs, local;

fs = require('fs');

local = {
  recurse: function(path) {
    return console.log({
      recurse: path
    });
  }
};

module.exports = function(opts) {
  var error, path, stat;
  if ('string' === typeof opts) {
    path = opts;
    try {
      stat = fs.lstatSync(path);
      if (stat.isDirectory()) {
        return local.recurse(path);
      }
    } catch (_error) {
      error = _error;
      return console.log(error);
    }
  }
};

module.exports._testInstance = local;
